name: Deploy to GKE

on:
  push:
    branches: 
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Decode Google Cloud credentials
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ./gcp-sa-key.json

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ./gcp-sa-key.json
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        version: latest
        export_default_credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set JSON key as output
      id: set_sa_key
      run: echo "::set-output name=sa_key::$(cat ./gcp-sa-key.json)"
      
    - name: Login to Google Container Registry
      uses: docker/login-action@v1 
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ steps.set_sa_key.outputs.sa_key }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./app
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world:latest

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials my-gke-cluster --zone us-central1-c
        helm upgrade --install hello-world ./chart --wait
